apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-express
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://gitlab.au.dk/swwao/f2025/exams-projects/Group-7/gitops.git"
    targetRevision: main
    path: base/tools/mongo-express
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# Denne fil fortæller ArgoCD at den skal deployere Mongo Express ressourcerne fra Git til Kubernetes.
# Den peger på base/tools/mongo-express mappen hvor Mongo Express ressourcerne ligger.