apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: payment-service
spec:
  podSelector: {} # Apply to all pods in payment-service namespace
  policyTypes:
    - Egress
  
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system 
      ports:
        - protocol: UDP
          port: 53    
        - protocol: TCP
          port: 53

# Denne NetworkPolicy tillader pods i payment-service at bruge DNS 
# -- altså at oversætte navne som "rabbitmq.rabbitmq.svc.cluster.local" til IP-adresser.

# UDP port 53 - for hurtige, små DNS-forespørgsler
# TCP port 53 - for større DNS-svar eller når UDP ikke virker
