# Allow payment service pods to perform DNS lookups - essential for service discovery
# Without this, pods cannot resolve service names like "rabbitmq.rabbitmq.svc.cluster.local"
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: payment-service
spec:
  podSelector: {} # Apply to all pods in payment-service namespace
  policyTypes:
    - Egress
  
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system # Target kube-system namespace where DNS runs
      ports:
        - protocol: UDP
          port: 53    
        - protocol: TCP
          port: 53