apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-rabbitmq-sqlserver
  namespace: payment-service
spec:
  podSelector: {} # Apply to all pods in payment-service namespace
  policyTypes:
  - Egress

  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: rabbitmq 
      ports:
        - protocol: TCP
          port: 5672 

    - to: 
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: sqlserver 
      ports:
        - protocol: TCP
          port: 1433 

# TCP port 5672 - AMQP protocol port for RabbitMQ messaging
# TCP port 1433 - Standard SQL Server port for database forbindelser

# AMQP (Advanced Message Queuing Protocol) er en standard måde for applikationer at sende beskeder til hinanden på.