apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - configmap.yaml
  - sealed-db-secret.yaml
  - sealed-rabbitmq-secret.yaml

# En kustomization fil er en liste over alle YAML-filer der skal 
# bruges sammen for at bygge en komplet Kubernetes applikation.