apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-nginx
  namespace: mongo-express
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mongo-express
  policyTypes:
    - Ingress
  
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8081

# Nginx er en webserver der i dit Kubernetes cluster fungerer som Ingress Controller
# Denne fil tillader indgående trafik til mongo-express fra nginx Ingress Controller
