apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express-ingress
  namespace: mongo-express
spec:
  ingressClassName: nginx
  rules:
    - host: swwao-courses.orbit.au.dk
      http:
        paths:
          - path: /grp-7/mongo-express
            pathType: Prefix
            backend:
              service:
                name: mongo-express
                port:
                  number: 8081
