---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express
  namespace: mongo-express
data:
  site-cookie-secret: "MWpIWHNUaEExVVhidXpuTEVISkRpSzBvT0VQalFqTUg="
  site-session-secret: "RWx6NUVudlJQUnRPOHlrSTd2WlNtSmI0bllWN2hXNmY="
type: Opaque
