apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  namespace: api-gateway
spec:
  ingressClassName: nginx
  rules:
    - host: swwao-courses.orbit.au.dk
      http:
        paths:
          - path: /grp-7/api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
