apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mssql-init
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://gitlab.au.dk/swwao/f2025/exams-projects/Group-7/gitops.git"
    targetRevision: main
    path: base/databases/mssql
  destination:
    server: https://kubernetes.default.svc
    namespace: sqlserver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# Denne fil fortæller ArgoCD at den skal køre database-setup jobbet automatisk efter SQL Server er deployeret.
# Den peger på base/databases/mssql mappen hvor MSSQL initialization Job ligger.