---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb
  namespace: mongodb
spec:
  encryptedData:
    mongodb-root-password: AgCB8BXXulH0pw6BWNHuFd7CiURIiCmw2oiQebdM8wJGITgAYa7DGt0nrJfQpOwVTmvPjVSf2ZEpAVArNNa86gkY90JTeJRhGxoQFbvIfSrvUIfa8tUAbY3l7mMHmVDRMSlpeTifKwllCSuO596e6xWiLmsYAJFWER6DGNG/baaCPsPmLQHSR+7m0txKjLdOfymNGr1fYJapzWrKkptqI4lWZh4OE8ik5XaTSyNsk+/OP4eZi/55N6z8/iVQyyRfngl/VVqnl4ixDu+2Zsi5Ti++spakFIj9bRbF18Og+3xzFxKn4uokcM/AUmULpwDEnINA2M9wZVdknc6rmHsz2Rkr+Nuc3umcs5ByKMCWFFnI7s4rxsSoGsxYpMSXwqk1z2c+Bax2QC9/rqj8ZDSQSxZkLkaZLY9L6ahtMuthwD7qqc6gWnuTSL2rVp+xAg87u6Osjw3osk10sA/ClBjsCObMbJE3ElYYAtONZ6zSU6ovjOaN3pyjJiCQjjTiAewf8qNiBWf15Seggq41PrmU5VgmLpaXk8T09q2MSU39WtKY4Kyfw+cdSiilbrqLYdvm3MKSN076xP5lstgdWmJxwnys73Jp7Yz2J8ka6yxdU0OL+YdR4WJcy0om8KBmpo7JORqhbX05rcPwiEZkMijeolLmN8fHo7eRLML2MhYf9lRkb0cRaiyL+9eQL1j+t/L6wu4MVvrj3Q==
