apiVersion: v1
kind: Secret
metadata:
  name: bitnamicharts-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: registry-1.docker.io/bitnamicharts  
  name: bitnamicharts-oci  
  type: helm  
  enableOCI: "true"