apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apply-mssql-job.yaml
      
configMapGenerator:
  - name: setup-mssql-db
    files:
      - setup-mssql-db.sql
    options:
      disableNameSuffixHash: true