apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apply-mssql-job.yaml
      
configMapGenerator:
  - name: setup-mssql-db
    files:
      - setup-mssql-db.sql
    options:
      disableNameSuffixHash: true   

# configMapGenerator tager filen setup-mssql-db.sql og pakker den automatisk ind i en ConfigMap med navnet setup-mssql-db.