apiVersion: v1
kind: Service
metadata:
  name: order-tracking-service
  namespace: order-tracking-service
  labels:
    app: order-tracking-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: order-tracking-service
