apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restaurant-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://gitlab.au.dk/swwao/f2025/exams-projects/Group-7/gitops.git"
    targetRevision: main
    path: base/services/restaurant-service
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# Denne fil fortæller ArgoCD at den skal deployere Restaurant Service ressourcerne fra Git til Kubernetes.
# Den peger på base/services/restaurant-service mappen hvor Restaurant Service ressourcerne ligger.